"""init auth router

Revision ID: 05daefb5732b
Revises: b46875e40007
Create Date: 2023-07-02 00:04:42.798480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05daefb5732b'
down_revision = 'b46875e40007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
