"""Init recipe

Revision ID: 275df5cd590d
Revises: b88c8098b6bb
Create Date: 2023-07-01 17:40:53.297630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275df5cd590d'
down_revision = 'b88c8098b6bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
