"""fix recipe and user

Revision ID: f4f39f01660f
Revises: 275df5cd590d
Create Date: 2023-07-01 17:50:57.156752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f39f01660f'
down_revision = '275df5cd590d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('submitter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'users', ['submitter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'submitter_id')
    # ### end Alembic commands ###
