"""refactor Recipe

Revision ID: f6009380916f
Revises: 1b3cc6ea5dd3
Create Date: 2023-07-01 19:14:26.094547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6009380916f'
down_revision = '1b3cc6ea5dd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('label', sa.String(length=256), nullable=False))
    op.add_column('recipes', sa.Column('url', sa.String(length=256), nullable=True))
    op.add_column('recipes', sa.Column('source', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_recipes_url'), 'recipes', ['url'], unique=False)
    op.drop_column('recipes', 'name')
    op.drop_column('recipes', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_recipes_url'), table_name='recipes')
    op.drop_column('recipes', 'source')
    op.drop_column('recipes', 'url')
    op.drop_column('recipes', 'label')
    # ### end Alembic commands ###
